import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/language_provider.dart';

class AppStrings {
  static String get(BuildContext context, String key) {
    final isArabic = Provider.of<LanguageProvider>(context, listen: false).isArabic;
    return isArabic ? (_ar[key] ?? _en[key] ?? key) : (_en[key] ?? key);
  }

  static const String parentRole = 'parent';
  static const String childRole = 'child';
  static const String pending = 'pending';
  static const String completed = 'completed';
  static const String approved = 'approved';
  static const String rejected = 'rejected';

  static const Map<String, String> _en = {
    'appName': 'Hero Mission',
    'tagline': 'Start your adventure 🚀',
    'version': 'Version 1.0.0',
    'signInParent': 'Sign in with Google',
    'iAmAChild': "I'm a Kid! 🎮",
    'parentHint': 'Parents use Google Sign-In to manage tasks',
    'welcomeParent': 'Welcome, Parent! 👋',
    'setupAccount': "Let's set up your account",
    'parentAccount': 'Parent Account',
    'parentDesc': 'Create missions • Approve tasks • Track progress',
    'yourName': 'Your Name',
    'letsGo': "Let's Go! 🚀",
    'signOut': 'Sign Out',
    'chooseHero': 'Choose Your Hero! ⚔️',
    'enterPin': 'Enter Your PIN',
    'wrongPin': 'Wrong PIN! Try again 🔒',
    'letsPlay': "Let's Play! 🎮",
    'noHeroes': 'No heroes yet!\nAsk a parent to create your account.',
    'myHeroes': 'My Heroes 🏆',
    'addHero': 'Add Hero',
    'heroName': "Hero's Name",
    'pin4': '4-digit PIN',
    'chooseAvatar': 'Choose Avatar:',
    'saveAvatar': 'Save Avatar',
    'createHero': 'Create Hero!',
    'cancel': 'Cancel',
    'heroReady': 'is ready to quest! 🎉',
    'deleteHero': 'Delete Hero? 🗑️',
    'deleteHeroConfirm': 'This will remove all their progress, tasks, and rewards permanently.',
    'delete': 'Delete',
    'deleteSuccess': 'Hero deleted successfully',
    'deleteError': 'Error deleting hero',
    'noHeroesYet': 'No Heroes Yet!',
    'noHeroesHint': 'Tap "Add Hero" to create your\nfirst child account.',
    'addNewHero': 'Add New Hero 🦸',
    'pleaseFillFields': 'Please fill name and 4-digit PIN!',
    'hey': 'Hey,',
    'recentTasks': 'Recent Tasks',
    'seeAll': 'See All',
    'allCaughtUp': 'All caught up!\nAsk a parent for more tasks.',
    'level': 'Level',
    'myMissions': '⚔️ My Missions',
    'all': 'All',
    'active': 'Active',
    'done': 'Done',
    'nothingHere': 'Nothing here yet!',
    'missionsWillAppear': 'Missions will appear here\nonce assigned.',
    'rewardsShop': '🎁 Rewards Shop',
    'coinsAvailable': 'Available to spend',
    'noRewardsYet': 'No rewards yet!',
    'noRewardsHint': 'Ask a parent to add some\nawesome rewards!',
    'redeemReward': 'Redeem Reward? 🎁',
    'redeem': 'Redeem!',
    'redeemSuccess': '🎉 Reward redeemed! Show it to your parent!',
    'notEnoughCoins': '❌ Not enough coins!',
    'myProgress': '📈 My Progress',
    'coins': 'Coins',
    'medalCollection': '🏅 Medal Collection',
    'approvals': 'Approvals',
    'approve': 'Approve ✅',
    'reject': 'Reject ❌',
    'settings': 'Settings',
    'language': 'Language',
    'arabic': 'Arabic',
    'english': 'English',
    'darkMode': 'Dark Mode',
    'darkModeOn': 'Dark mode is on',
    'lightModeOn': 'Light mode is on',
    'profile': 'Profile',
    'aboutApp': 'About App',
    'settingsDesc': 'Change app language and other preferences',
    'completeMission': 'Complete Mission ⚔️',
    'waitingApproval': 'Waiting for approval...',
    'submittedBy': 'Submitted by',
    'streakDays': 'd',
    'streakDay': 'd',
    'xpProgress': 'XP Progress',
    'xpToNext': 'XP to next level',
    'levelLabel': 'Level',
    'badgesLabel': 'Badges 🏅',
    'recentRewards': 'Recent Rewards 🎁',
    'redeemed': 'Redeemed:',
    'needsApproval': 'Needs Approval ✅',
    'assignedMissions': 'Assigned Missions 🎯',
    'noActiveMissions': 'No active missions for this hero.',
    'assignNewMission': 'Assign New Mission',
    'addReward': 'Add Reward 🎁',
    'rewardName': 'Reward Name (e.g. Ice Cream)',
    'coinCost': 'Coin Cost (e.g. 100)',
    'rewardAddedSuccess': 'Reward added successfully!',
    'rewardAddedError': 'Error adding reward',
    'enterValidReward': 'Please enter a valid title and cost!',
    'rewardsButton': 'Rewards',
    'childProgress': "'s Progress",
    'justNow': 'Just now',
    'deleteTask': 'Delete Mission 🗑️',
    'deleteTaskConfirm': 'Delete this mission permanently?',
    'deleteTaskSuccess': '🗑️ Mission deleted.',
    'deleteTaskError': 'Error deleting mission.',
    'missionApprovals': 'Mission Approvals ✅',
    'allClear': 'All Clear!',
    'noPendingApprovals': 'No missions waiting for approval.',
    'approveSuccess': '✅ Mission approved! Coins awarded!',
    'approveError': 'Error approving task',
    'rejectMsg': '❌ Mission rejected.',
    'badge_novice_title': 'Hero Novice',
    'badge_novice_desc': 'Earned 50 XP. Your journey begins!',
    'badge_apprentice_title': 'Hero Apprentice',
    'badge_apprentice_desc': 'Earned 300 XP. Getting stronger!',
    'badge_knight_title': 'Hero Knight',
    'badge_knight_desc': 'Earned 750 XP. A true warrior!',
    'badge_master_title': 'Hero Master',
    'badge_master_desc': 'Earned 1400 XP. Almost unstoppable!',
    'badge_legend_title': 'Hero Legend',
    'badge_legend_desc': 'Earned 2250 XP. You are a legendary hero!',
    'unlocked': 'UNLOCKED',
    'locked': 'LOCKED',
    'completed_badge': 'Completed',
    'next': 'Next',
    'xpLabel': 'XP',
    'levelShort': 'Lv.',
    'maxLevel': '🏆 MAX!',
    'avatarUpdated': 'Avatar updated! 🎉',
    'pleaseEnterName': 'Please enter your name!',
    'pleaseAssignMission': 'Please assign this mission to a hero!',
    'missionCreated': 'Mission created! ⚔️',
    'pleaseSelectHero': 'Select a hero',
    'launchMission': 'Launch Mission!',
    'lvl_title_1': 'Newbie',
    'lvl_title_2': 'Rookie',
    'lvl_title_3': 'Explorer',
    'lvl_title_4': 'Adventurer',
    'lvl_title_5': 'Champion',
    'lvl_title_6': 'Hero',
    'lvl_title_7': 'Warrior',
    'lvl_title_8': 'Legend',
    'lvl_title_9': 'Master',
    'lvl_title_10': 'Grand Master',
    'tapToPlay': 'Tap to Play!',
    'newMission': 'New Mission ⚔️',
    'missionTitle': 'Mission Title',
    'missionDesc': 'Description (optional)',
    'easy': 'Easy 🟢',
    'medium': 'Medium 🟡',
    'hard': 'Hard 🔴',
    'difficultyLevel': 'Difficulty Level 🎚️',
    'coinReward': 'Coin Reward 🪙',
    'deadlineOptional': 'Deadline (optional)',
    'assignToHero': 'Assign to Hero',
    'noChildrenError': 'No heroes yet! Add a child first.',
    'missionTitleHint': 'e.g. Clean your room',
    'missionDescHint': 'Add details about this mission...',
    'noDeadlineHint': 'No deadline — pick a date',
    'enterTitle': 'Enter a title',
    'hello': 'Hello,',
    'missionCompleteTitle': 'Mission Complete!',
    'trueHero': "You're a true hero!",
    'coinsEarnedLabel': 'Coins Earned',
    'continueAdventure': 'Continue Adventure',
    'dangerZone': 'Danger Zone',
    'resetAppData': 'Reset All App Data',
    'resetDesc': 'Delete all children, tasks, rewards, and progress',
    'resetConfirmTitle': 'Reset Everything? ⚠️',
    'resetConfirmDesc': 'This will permanently delete ALL data related to your children. This cannot be undone!',
    'resetting': 'Resetting...',
  };

  static const Map<String, String> _ar = {
    'appName': 'مهمة البطل',
    'tagline': 'ابدأ مغامرتك 🚀',
    'version': 'الإصدار 1.0.0',
    'signInParent': 'الدخول عبر جوجل',
    'iAmAChild': 'أنا بطل صغير! 🎮',
    'parentHint': 'الآباء يستخدمون جوجل لإدارة المهام',
    'welcomeParent': 'أهلاً بك أيها الأب! 👋',
    'setupAccount': 'لنقم بإعداد حسابك',
    'parentAccount': 'حساب الأب',
    'parentDesc': 'إنشاء المهام • الموافقة • متابعة التقدم',
    'yourName': 'اسمك',
    'letsGo': 'هيا بنا! 🚀',
    'signOut': 'تسجيل الخروج',
    'chooseHero': 'اختر بطلك! ⚔️',
    'enterPin': 'أدخل الرمز السري',
    'wrongPin': 'الرمز خاطئ! حاول مجدداً 🔒',
    'letsPlay': 'هيا نلعب! 🎮',
    'noHeroes': 'لا يوجد أبطال بعد!\nاطلب من والدك إنشاء حساب لك.',
    'myHeroes': 'أبطالي 🏆',
    'addHero': 'إضافة بطل',
    'heroName': 'اسم البطل',
    'pin4': 'رمز سري (4 أرقام)',
    'chooseAvatar': 'اختر الأفاتار:',
    'saveAvatar': 'حفظ الصورة الرمزية',
    'createHero': 'إنشاء البطل!',
    'cancel': 'إلغاء',
    'heroReady': 'جاهز للمغامرة! 🎉',
    'deleteHero': 'حذف البطل؟ 🗑️',
    'deleteHeroConfirm': 'سيتم حذف جميع التقدم والمهام والمكافآت بشكل دائم.',
    'delete': 'حذف',
    'deleteSuccess': 'تم حذف البطل بنجاح',
    'deleteError': 'خطأ في حذف البطل',
    'noHeroesYet': 'لا يوجد أبطال بعد!',
    'noHeroesHint': 'اضغط "إضافة بطل" لإنشاء\nأول حساب لطفلك.',
    'addNewHero': 'إضافة بطل جديد 🦸',
    'pleaseFillFields': 'يرجى ملء الاسم والرمز السري (4 أرقام)!',
    'hey': 'مرحباً،',
    'recentTasks': 'المهام الأخيرة',
    'seeAll': 'عرض الكل',
    'allCaughtUp': 'أحسنت! انتهيت من كل المهام!\nاطلب من والدك مهام جديدة.',
    'level': 'المستوى',
    'myMissions': '⚔️ مهامي',
    'all': 'الكل',
    'active': 'نشط',
    'done': 'منتهي',
    'nothingHere': 'لا شيء هنا بعد!',
    'missionsWillAppear': 'ستظهر المهام هنا\nعند تعيينها.',
    'rewardsShop': '🎁 متجر المكافآت',
    'coinsAvailable': 'متاح للصرف',
    'noRewardsYet': 'لا توجد مكافآت بعد!',
    'noRewardsHint': 'اطلب من والدك إضافة\nمكافآت رائعة!',
    'redeemReward': 'استبدال مكافأة؟ 🎁',
    'redeem': 'استبدل!',
    'redeemSuccess': '🎉 تم استبدال المكافأة! أظهرها لوالدك!',
    'notEnoughCoins': '❌ عملاتك غير كافية!',
    'myProgress': '📈 تقدمي',
    'coins': 'عملة',
    'medalCollection': '🏅 مجموعة الأوسمة',
    'approvals': 'الطلبات',
    'approve': 'موافقة ✅',
    'reject': 'رفض ❌',
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'arabic': 'العربية',
    'english': 'الإنجليزية',
    'darkMode': 'الوضع الليلي',
    'darkModeOn': 'الوضع الليلي مفعّل',
    'lightModeOn': 'الوضع النهاري مفعّل',
    'profile': 'الملف الشخصي',
    'aboutApp': 'عن التطبيق',
    'settingsDesc': 'تغيير لغة التطبيق والتفضيلات الأخرى',
    'completeMission': 'إتمام المهمة ⚔️',
    'waitingApproval': 'بانتظار الموافقة...',
    'submittedBy': 'أرسل من',
    'streakDays': 'ي',
    'streakDay': 'ي',
    'xpProgress': 'تقدم نقاط الخبرة',
    'xpToNext': 'نقطة خبرة للمستوى التالي',
    'levelLabel': 'المستوى',
    'badgesLabel': 'الأوسمة 🏅',
    'recentRewards': 'آخر المكافآت 🎁',
    'redeemed': 'تم استبدال:',
    'needsApproval': 'يحتاج موافقة ✅',
    'assignedMissions': 'المهام المعينة 🎯',
    'noActiveMissions': 'لا توجد مهام نشطة لهذا البطل.',
    'assignNewMission': 'تعيين مهمة جديدة',
    'addReward': 'إضافة مكافأة 🎁',
    'rewardName': 'اسم المكافأة (مثال: آيس كريم)',
    'coinCost': 'تكلفة العملة (مثال: 100)',
    'rewardAddedSuccess': 'تمت إضافة المكافأة بنجاح!',
    'rewardAddedError': 'خطأ في إضافة المكافأة',
    'enterValidReward': 'يرجى إدخال عنوان وتكلفة صحيحين!',
    'rewardsButton': 'المكافآت',
    'childProgress': ' تقدم',
    'justNow': 'للتو',
    'deleteTask': 'حذف المهمة 🗑️',
    'deleteTaskConfirm': 'حذف هذه المهمة نهائياً؟',
    'deleteTaskSuccess': '🗑️ تم حذف المهمة.',
    'deleteTaskError': 'خطأ في حذف المهمة.',
    'missionApprovals': 'طلبات الموافقة ✅',
    'allClear': 'كل شيء على ما يرام!',
    'noPendingApprovals': 'لا توجد مهام بانتظار الموافقة.',
    'approveSuccess': '✅ تمت الموافقة! تمت إضافة العملات!',
    'approveError': 'خطأ في الموافقة',
    'rejectMsg': '❌ تم رفض المهمة.',
    'badge_novice_title': 'البطل المبتدئ',
    'badge_novice_desc': 'جمعت 50 نقطة خبرة. رحلتك بدأت للتو!',
    'badge_apprentice_title': 'البطل المتدرب',
    'badge_apprentice_desc': 'جمعت 300 نقطة خبرة. أصبحت أقوى!',
    'badge_knight_title': 'الفارس الشجاع',
    'badge_knight_desc': 'جمعت 750 نقطة خبرة. محارب حقيقي!',
    'badge_master_title': 'المعلم الأكبر',
    'badge_master_desc': 'جمعت 1400 نقطة خبرة. لا أحد يستطيع إيقافك!',
    'badge_legend_title': 'أسطورة الأبطال',
    'badge_legend_desc': 'جمعت 2250 نقطة خبرة. أنت الآن بطل أسطوري!',
    'unlocked': 'مفتوح',
    'locked': 'مغلق',
    'completed_badge': 'مكتمل',
    'next': 'التالي',
    'xpLabel': 'نقطة',
    'levelShort': 'م.',
    'maxLevel': '🏆 الحد الأقصى!',
    'avatarUpdated': 'تم تحديث الصورة! 🎉',
    'pleaseEnterName': 'يرجى إدخال اسمك!',
    'pleaseAssignMission': 'يرجى تحديد بطل لهذه المهمة!',
    'missionCreated': 'تم إنشاء المهمة! ⚔️',
    'pleaseSelectHero': 'اختر بطلاً',
    'launchMission': 'أطلق المهمة!',
    'lvl_title_1': 'المبتدئ',
    'lvl_title_2': 'المتدرب',
    'lvl_title_3': 'المستكشف',
    'lvl_title_4': 'المغامر',
    'lvl_title_5': 'البطل',
    'lvl_title_6': 'الفارس',
    'lvl_title_7': 'المحارب',
    'lvl_title_8': 'الأسطورة',
    'lvl_title_9': 'المعلم',
    'lvl_title_10': 'الغراند ماستر',
    'tapToPlay': 'اضغط للعب!',
    'newMission': 'مهمة جديدة ⚔️',
    'missionTitle': 'عنوان المهمة',
    'missionDesc': 'الوصف (اختياري)',
    'easy': 'سهل 🟢',
    'medium': 'متوسط 🟡',
    'hard': 'صعب 🔴',
    'difficultyLevel': 'مستوى الصعوبة 🎚️',
    'coinReward': 'مكافأة العملات 🪙',
    'deadlineOptional': 'الموعد النهائي (اختياري)',
    'assignToHero': 'تعيين للبطل',
    'noChildrenError': 'لا يوجد أبطال! أضف طفلاً أولاً.',
    'missionTitleHint': 'مثال: تنظيف الغرفة',
    'missionDescHint': 'أضف تفاصيل عن هذه المهمة...',
    'noDeadlineHint': 'بدون موعد - اختر تاريخاً',
    'enterTitle': 'أدخل عنواناً',
    'hello': 'أهلاً،',
    'missionCompleteTitle': 'تمت المهمة بنجاح!',
    'trueHero': 'أنت بطل حقيقي!',
    'coinsEarnedLabel': 'عملات مكتسبة',
    'continueAdventure': 'استمرار المغامرة',
    'dangerZone': 'منطقة الخطر',
    'resetAppData': 'مسح كافة بيانات التطبيق',
    'resetDesc': 'حذف جميع الأطفال والمهام والمكافآت والتقدم',
    'resetConfirmTitle': 'مسح كل شيء؟ ⚠️',
    'resetConfirmDesc': 'سيؤدي هذا إلى حذف جميع البيانات المتعلقة بأطفالك نهائياً. لا يمكن التراجع عن هذا الإجراء!',
    'resetting': 'جاري المسح...',
  };
}
